#!/bin/bash
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

# flash
# Flashcards right from your terminal
# Author: StationaryStation

# Change this if you want to store flashcards elsewhere
flashcards_dir=~/flash

init() {
	echo "Flashcards directory not found... Creating"
	mkdir -p $flashcards_dir
}

read_flashcard() {
	should_flash=0
	short=""
	long=""
	if [ "$1" ] && [ -f "$flashcards_dir/$1.flash" ]; then
		flashcard_path=$flashcards_dir/$1.flash
		while IFS= read -r line
		do
			if [ "$line" == '---' ]; then
				should_flash=1
			fi

			case $should_flash in
				0)
					short=$line
					;;
				1)
					long="$long
$line"
					;;
			esac
		done < "$flashcard_path"

		echo "$short"
		echo "press any key to continue..."
		while [ true ] ; do
			read -t 3 -n 1
			if [ $? = 0 ] ; then
				echo "$long"
				exit
			fi
		done
	elif [ "$1" ]; then
		echo "Flashcard not found"
	else
		echo "You need to provide a flashcard name"
	fi
}

create_flashcard() {
	touch "$flashcards_dir/$1.flash"
	$EDITOR "$flashcards_dir/$1.flash"
}

help_func() {
	echo "Flash"
	echo "Small flashcards utility"
	echo "---"
	echo "new <filename>"
	echo "creates a new flashcard and edit it"
	echo "---"
	echo "open <filename>"
	echo "open a flashcard"
	echo "---"
	echo "edit <filename>"
	echo "edit a flashcard file"
	echo "---"
	echo "list"
	echo "list all flashcards in ~/flash"
	echo "---"
	echo "help"
	echo "show this menu"
	echo "---"
	echo "USAGE: flashcards are separated using '---'"
	echo "Top is the flashcard hint"
	echo "Bottom is the flashcard content"
}

if [ ! -d "$flashcards_dir" ]; then
	init
else
	case $1 in
		"new")
			create_flashcard "$2"
			;;
		"help")
			help_func
			;;
		"edit")
			$EDITOR "$flashcards_dir/$2.flash"
			;;
		"open")
			read_flashcard "$2"
			;;
		"list")
			ls $flashcards_dir
			;;
		*)
			help_func
			;;
	esac
fi
