#!/bin/bash
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>. 

## TODOCLI
## Cool lightweight app made by StationaryStation

current_date=$(date +%F)

create_todo() {
	mkdir -p ~/todo
	
	if [ "$1" ]; then
	       if [ "$1" == "daily" ]; then
			touch ~/todo/${current_date}.todo
			echo "Created todo in ~/todo/ as ${current_date}.todo"
		else
			touch ~/todo/${1}.todo
			echo "Created todo in ~/todo/ as ${1}.todo"
	       fi
	else
		echo "You need to provide a name"
	fi
}

edit_todo() {
	if [ "$1" ] && [ -f ~/todo/$1.todo ]; then
		vim ~/todo/${1}.todo
	elif [ "$1" == "daily" ] && [ -f ~/todo/${current_date}.todo ]; then
		vim ~/todo/${current_date}.todo
	else
		echo "Todo not found..."
	fi
}

delete_todo() {
	if [ -f ~/todo/${1}.todo ]; then
		rm ~/todo/${1}.todo
		echo "deleted ${1}"
	else
		echo "Todo not found"
	fi
}

list_todo() {
	ls -lh ~/todo
}

case "$1" in
	"new")
		create_todo "$2"
		;;
	"edit")
		edit_todo "$2"
		;;
	"delete")
		delete_todo "$2"
		;;
	"list")
		list_todo
		;;
	*)
		echo "Usage:"
		echo "new: create new todo file"
		echo "edit: edit a todo file"
		echo "delete: delete a todo file"
		echo "list: lists all todo files"
		;;
esac
