#!/bin/bash
## TODOCLI
## Cool lightweight app made by StationaryStation

current_date=$(date -I)

create_todo() {
	mkdir -p ~/todo
	
	if [ "$1" ]; then
	       if [ "$1" == "daily" ]; then
			touch ~/todo/${current_date}.todo
			echo "Created todo in ~/todo/ as ${current_date}.todo"
		else
			touch ~/todo/${1}.todo
			echo "Created todo in ~/todo/ as ${1}.todo"
	       fi
	else
		echo "You need to provide a name"
	fi
}

edit_todo() {
	if [ "$1" ] && [ -f ~/todo/$1.todo ]; then
		vim ~/todo/${1}.todo
	elif [ "$1" == "daily" ] && [ -f ~/todo/${current_date}.todo ]; then
		vim ~/todo/${current_date}.todo
	else
		echo "Todo not found..."
	fi
}

delete_todo() {
	if [ -f ~/todo/${1}.todo ]; then
		rm ~/todo/${1}.todo
		echo "deleted ${1}"
	else
		echo "Todo not found"
	fi
}

list_todo() {
	ls -lh ~/todo
}

case "$1" in
	"new")
		create_todo "$2"
		;;
	"edit")
		edit_todo "$2"
		;;
	"delete")
		delete_todo "$2"
		;;
	"list")
		list_todo
		;;
	*)
		echo "Usage:"
		echo "new: create new todo file"
		echo "edit: edit a todo file"
		echo "delete: delete a todo file"
		echo "list: lists all todo files"
		;;
esac
